"""added FK constraint between game and playtime_recommendations

Revision ID: 1230d54c58c8
Revises: 53c314b0b2e9
Create Date: 2025-05-20 15:39:34.833600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1230d54c58c8'
down_revision: Union[str, None] = '53c314b0b2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playtime_recommendations', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'playtime_recommendations', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playtime_recommendations', type_='foreignkey')
    op.drop_column('playtime_recommendations', 'game_id')
    # ### end Alembic commands ###
