"""Renamed playtime_recommendations to recommendations

Revision ID: c07fa1005750
Revises: 1230d54c58c8
Create Date: 2025-05-21 09:31:57.087829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c07fa1005750'
down_revision: Union[str, None] = '1230d54c58c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_interval', sa.Enum('ZERO_TO_FORTY_NINE', 'FIFTY_TO_NINETY_NINE', 'HUNDRED_TO_HUNDRED_NINETY_NINE', 'TWO_HUNDRED_TO_FOUR_HUNDRED_NINETY_NINE', 'FIFE_HUNDRED_PLUS', name='time_interval'), nullable=False),
    sa.Column('sum_recommended', sa.Integer(), nullable=False),
    sa.Column('sum_not_recommended', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('playtime_recommendations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playtime_recommendations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('time_interval', mysql.ENUM('ZERO_TO_FORTY_NINE', 'FIFTY_TO_NINETY_NINE', 'HUNDRED_TO_HUNDRED_NINETY_NINE', 'TWO_HUNDRED_TO_FOUR_HUNDRED_NINETY_NINE', 'FIFE_HUNDRED_PLUS'), nullable=False),
    sa.Column('sum_recommended', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sum_not_recommended', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='playtime_recommendations_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_uca1400_ai_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.drop_table('recommendations')
    # ### end Alembic commands ###
